[package]
name = "bfr"
version = "0.1.0"
authors = ["Victor Hermann Chiletto <victor.vasconceloschiletto@gmail.com>"]
edition = "2018"
license = "Unlicense"


[dependencies]
snafu = "0.6.2"
tinyvec = "0.3.0"
itertools = "0.8.2"
structopt = "0.3.8"
clap = "2.33.0"
libc = "0.2.66"
